838 signer implement last low priority methods
vechain/vechain-sdk-js pull request #1004
Opened 2024-06-21 12:06 UTC by lucanicoladebiasi

# Description

* EIP-191 `signMessage` and and EIP-712 `signTypedData` implemented.
* `packages/core/src/utils/txt/txt.ts` introduces the `txt.encode` and `txt.decode` methods to enforce consistent text-binary codec.

# Fixes # (issue)

Text codec implemented enforcing a consistent `NFC` unicode normalisation for utf-8 binary representation.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `yarn test:solo`
- [x] `yarn test:unit`

**Test Configuration**:
* Node.js Version: v20.14.0
* Yarn Version: 1.22.22

# Checklist:

- [x] My code follows the coding standards of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing integration tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-06-24 08:13 UTC, rodolfopietro97 requested changes
@lucanicoladebiasi Great work.
Only 2 few things:
* 2 feedback (1 is only a question)
* And other one is why implementing and change some crypto stuff in a pr related to signer low priority method. BUT no problem on that, it is only a question

2024-06-24 08:13 UTC, rodolfopietro97 commented on packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
> +                        ethers.TypedDataEncoder.hash(domain, types, value)
HI @lucanicoladebiasi can we substitute ethers here in the future?

2024-06-24 08:13 UTC, rodolfopietro97 commented on packages/network/tests/signer/signers/vechain-private-key-signer/fixture.ts
> +interface TestCaseTypedDataDomain {
Can you add more comments on types?

2024-06-24 13:05 UTC, lucanicoladebiasi commented on packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
> +                        ethers.TypedDataEncoder.hash(domain, types, value)
Yes, and you know I'm a strong advocate to do not use `ethers`, but for this function this is not possible now. The `signTypeData` method leverages on ABI codec, we haven't our implementation yet, hence until we do not provide our oroginal ABI codec doesn't make sense to do the same `ethers.TypedDataEncoder.hash(domain, types, value)`.

2024-06-24 16:27 UTC, rodolfopietro97 commented on packages/network/tests/signer/signers/vechain-private-key-signer/fixture.ts
> +interface TestCaseTypedDataDomain {
https://github.com/vechain/vechain-sdk-js/pull/1004/commits/c7bd734f09ceed21b3a996a542a2f371d375350c

2024-06-24 16:27 UTC, rodolfopietro97 commented on packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
> +                        ethers.TypedDataEncoder.hash(domain, types, value)
lgtm

2024-06-25 07:41 UTC, rodolfopietro97 approved these changes

2024-06-25 08:48 UTC, merged