1031 dedicated package for thor solo accounts and constants
vechain/vechain-sdk-js pull request #1059
Opened 2024-07-16 17:11 UTC by rodolfopietro97

# Description

Create dedicated Thor solo package

# Checklist:

- [x] Create package
- [x] Thor solo constants
- [x] Built in constants
- [x] Network constant (WIP)
- [  ] Check other constants
- [  ] Thor solo doc/tutorial
- [  ] Doc

2024-07-22 15:49 UTC, fabiorigam requested changes

2024-07-22 15:49 UTC, fabiorigam commented on packages/core/src/utils/txt/index.ts
> +export * from './txt';
What is this empty folder? do we need it?

2024-07-22 15:49 UTC, fabiorigam commented on packages/network/src/constant/built-in/index.ts
> +export * from './built-in';
Same here

2024-07-23 05:59 UTC, rodolfopietro97 commented on packages/core/src/utils/txt/index.ts
> +export * from './txt';
This was a missing export (note related to this PR, but I saw this and I correct).
If you see into `packages/core/src/utils/txt/` folder you will find the file

2024-07-23 06:00 UTC, rodolfopietro97 commented on packages/network/src/constant/built-in/index.ts
> +export * from './built-in';
Same here, see 'packages/network/src/constant/built-in' folder

2024-07-23 07:05 UTC, fabiorigam approved these changes

2024-07-23 12:14 UTC, merged