1114 class revision
vechain/vechain-sdk-js pull request #1175
Opened 2024-08-16 05:27 UTC by lucanicoladebiasi

# Description

The *VeChain Data Model* `packages/core/src/vcdm/Revision.ts` class replaces the `/utils/quantity` functional constant.

The *VeChain Data Model* `packages/core/src/vcdm/Quantity.ts` class replaces the `/utils/quantity` functional constant.

Documentation and examples provided.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `test yarn:examples`
- [x] `test yarn:solo`
- [x] `test yarn:unit` 

**Test Configuration**:
* Node.js Version: v20.14.0
* Yarn Version: 1.22.22

# Checklist:

- [x] My code follows the coding standards of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing integration tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-08-16 09:52 UTC, freemanzMrojo requested changes

2024-08-16 09:52 UTC, freemanzMrojo commented on packages/core/src/vcdm/Revision.ts
> +    /**
I think we should add a backwards compatibility part, otherwise those using `revisionUtils` will have errors when using this version. It would be just 2 methods as far as I see 👍

2024-08-17 06:42 UTC, lucanicoladebiasi commented on packages/core/src/vcdm/Revision.ts
> +    /**
I think we shouldn't add any back-compatibility if not absolutely needed because I think is positive to persuade developers to follow consistent programming patterns as the one proposed by the *VeChain Data Model* where `<Class>.of(<something>).isValid()` pattern is common instead of any specific `someUtility.isSome(<Thing.).

2024-08-17 11:43 UTC, freemanzMrojo approved these changes

2024-08-18 06:18 UTC, merged