refactor: 1162 transaction module in dev...
vechain/vechain-sdk-js pull request #1347
Opened 2024-09-25 07:49 UTC by lucanicoladebiasi

# Description

The module `packages/core/src/transaction` is refactored to be coherent with the *VeChain Data Model* using its classes as arguments to build transactions.

* `UInt8Array` type arguments preferred over `Buffer` type.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] 'yarn test:examples'
- [x] `yarn test:solo`
- [x] `yarn test:unit'

**Test Configuration**:
* Node.js Version: v22.8.0
* Yarn Version: 1.22.22

# Checklist:

- [x] My code follows the coding standards of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing integration tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-09-26 12:50 UTC, rodolfopietro97 approved these changes

2024-09-27 07:37 UTC, lucanicoladebiasi commented on packages/core/tests/transaction/Transaction.unit.test.ts
> +            test('of delegated transactions', () => {});
x

2024-09-27 16:09 UTC, freemanzMrojo requested changes
I just need some clarification about the `gas` usage 👍

2024-09-27 16:09 UTC, freemanzMrojo commented on packages/core/src/vcdm/Mnemonic.ts
> +     * @param that - The mnemonic to compare with.
Minor: `_that` is still underscored because it unused.

2024-09-27 16:09 UTC, freemanzMrojo commented on packages/core/src/transaction/Transaction.ts
> +    private static _computeUsedGasFor(data: string): number {
Minor, suggestion: I think it could make sense to get rid of the underscores at the beginning of the method names since we are not using that pattern everywhere. Feel free not to do it 👍

2024-09-30 10:07 UTC, freemanzMrojo approved these changes

2024-09-30 10:31 UTC, lucanicoladebiasi commented on packages/core/src/transaction/Transaction.ts
> +            gas: decodedRLPBody.gas as number,
`TransactionBody.gas` is a `number` or a string expressing the value of CTHO in *wei* in hexadecimal form. Between the two forms I prefer to avoid to use number and IEEE-754 approximation. I propose to leave is unchanged for compatibility reasons, but to rework gas computation in bigint and make our SDK always to encode gas in hexadecimal form of a natural number.

2024-09-30 10:35 UTC, lucanicoladebiasi commented on docs/examples/transactions/sign-decode.ts
> +const gas = Number(Transaction.intrinsicGas(clauses).wei);
Suggestion accepted in coherence with what wrote above. We prefer to express gas in wei in hexadecimal forms to avoid `number` types.

2024-09-30 10:38 UTC, lucanicoladebiasi commented on docs/examples/transactions/blockref-expiration.ts
> +    gas: HexUInt.of(Transaction.intrinsicGas(clauses).wei).toString(), // use thor.gas.estimateGas() for better estimation
`Transaction.intrinsicGas(clauses)` returns a `VTHO` object, hence to keep the compatibility with the code in the example I need to have its value in *wei*, it is a bigint and we prefer to represent a bigint as an exadecimal expression of a natural number.

2024-09-30 10:44 UTC, lucanicoladebiasi commented on packages/network/src/thor-client/gas/gas-module.ts
> +        const intrinsicGas = Number(Transaction.intrinsicGas(clauses).wei);
No, not always and this can be lead to approximation troubles. But to change the gas logic from number to bigint is somethig we should address in the specific ticket https://github.com/vechain/vechain-sdk-js/issues/1361 because it requires to review all the computations, out of `core` as well.

2024-09-30 10:46 UTC, lucanicoladebiasi commented on packages/core/src/transaction/Transaction.ts
> +    private static _computeUsedGasFor(data: string): number {
Suggestion accepted and implemented.

2024-09-30 11:16 UTC, merged