Remove ethers from core package
vechain/vechain-sdk-js pull request #1380
Opened 2024-10-03 09:16 UTC by fabiorigam

2024-10-04 06:39 UTC, rodolfopietro97 requested changes

2024-10-04 06:39 UTC, rodolfopietro97 commented on packages/network/tests/thor-client/contracts/fixture.ts
> +                    types: 'uint256',
are you sure it is correct?
I mean if we have more types: ['uint256', 'string', ...] we need to have an array as we current have

2024-10-04 06:54 UTC, fabiorigam commented on packages/network/tests/thor-client/contracts/fixture.ts
> +                    types: 'uint256',
@rodolfopietro97 Yeah, now it's:  `types: string | AbiParameter[];`
Sp if there are more types should be a AbiParameter[], as we are using viem now.

2024-10-04 13:57 UTC, freemanzMrojo commented on packages/network/tests/thor-client/contracts/fixture.ts
> +                    types: 'uint256',
Yep, it is what @fabiorigam said. `AbiParameter` is [based on `abitype` type](https://abitype.dev/api/types#abiparameter), which means passing an object.

I think it is possible that in the future we might need to get (at least partially) some of the backwards compatibility methods back in a different shape. We need to reflect in the release notes 100% the differences about `tuples` and `format`. Those notes should be about putting into words what those methods were doing. We might need to introduce a type similar to `ParamType`, but ours.

Anyways, the current changes look correct, will approve now.

2024-10-04 13:57 UTC, freemanzMrojo approved these changes

2024-10-07 09:55 UTC, rodolfopietro97 approved these changes

2024-10-07 12:58 UTC, merged