feat: Document all differences into rpc methods WRT standard
vechain/vechain-sdk-js pull request #1394
Opened 2024-10-07 14:50 UTC by rodolfopietro97

# Description

The most hated work of a software developer. The documentation 😅😂

P.S.
Please guys can you take a look? My english is not the best

@victhorbi @fabiorigam @Valazan @freemanzMrojo @lucanicoladebiasi

2024-10-07 15:14 UTC, fabiorigam requested changes

2024-10-07 15:57 UTC, leszek-vechain commented on packages/network/src/provider/utils/rpc-mapper/methods/eth_getBlockByHash/eth_getBlockByHash.ts
> + *                 * params[1]: The transaction hydrated detail flag. If true, the block will contain the transaction details, otherwise it will only contain the transaction hashes.
not sure if hydrated is ok in that context

2024-10-07 17:38 UTC, leszek-vechain commented on docs/provider.md
> +Vechain supports only the block number tags 'latest' and 'finalized'. 'earliest', 'safe', and 'pending' are not
we also support these: best stands for latest block, justified stands for the justified block, finalized stands for the finalized block

2024-10-07 17:39 UTC, leszek-vechain commented on docs/provider.md
> +More, this behaviot can be customized by the user.
typo

2024-10-07 18:28 UTC, leszek-vechain commented on docs/provider.md
> +### eth_gasPrice
did use eth_gasPrice, but I only got this: { jsonrpc: '2.0', result: '0x38d7ea4c68000', id: 1 }

2024-10-07 18:30 UTC, leszek-vechain commented on docs/provider.md
> +- Differences with RPC Standard: Some small differences related to the block number tag.ùù
some weird chars at the end of the line

2024-10-07 18:33 UTC, leszek-vechain commented on docs/provider.md
> +The fields 'difficulty','totalDifficulty','uncles','sha3Uncles','nonce','logsBloom','extraData','baseFeePerGas','
eth_syncing on solo returns this: { jsonrpc: '2.0', result: false, id: 67 }

2024-10-08 07:07 UTC, fabiorigam approved these changes

2024-10-08 07:17 UTC, merged