661 contract  event filtering
vechain/vechain-sdk-js pull request #715
Opened 2024-03-14 16:18 UTC by Valazan

2024-03-15 13:56 UTC, fabiorigam commented on packages/core/src/abi/fragment.ts
There is another ethers.EventFragment to substitute on this page

2024-03-15 17:27 UTC, rodolfopietro97 requested changes
@Valazan Is it tested over different methods or it is only for transfer (I give an on the fly look)

2024-03-18 11:51 UTC, Valazan commented
@rodolfopietro97 I've just added two additional contracts (one of them is the testing contract)

2024-03-18 13:25 UTC, fabiorigam commented on docs/templates/contracts.md
> +Once the contract is deployed, we can filter the Transfer event using the vechain SDK. The following code shows how to filter the Transfer event:
Can we add more details? We need to improve the docs

2024-03-18 13:25 UTC, fabiorigam commented on packages/network/src/thor-client/contracts/model/contract.ts
> +     */
Missing @returns

2024-03-18 14:16 UTC, fabiorigam approved these changes

2024-03-19 08:46 UTC, rodolfopietro97 approved these changes

2024-03-19 09:24 UTC, merged