Test sample apps when creating a new PR [WORK IN PROGRESS]
vechain/vechain-sdk-js pull request #716
Opened 2024-03-15 09:06 UTC by fabiorigam

2024-03-15 17:21 UTC, rodolfopietro97 commented on apps/vechain-sdk-nextjs/yarn.lock
Please remove this vechain-sdk-nextjs app, it is redundant

2024-03-19 08:35 UTC, rodolfopietro97 commented on apps/sdk-hardhat-integration/test/VechainHelloWorld.testnet.test.ts
> +        expect(true).to.be.true;
To replace in future hahahaha

2024-03-19 08:35 UTC, rodolfopietro97 commented on apps/sdk-nextjs-integration/src/app/page.tsx
> +                        // eslint-disable-next-line @typescript-eslint/no-misused-promises
Is this failing without the eslint-disable-next-line?

2024-03-19 08:37 UTC, rodolfopietro97 requested changes

2024-03-19 08:37 UTC, rodolfopietro97 commented on apps/sdk-node-integration/tests/index.test.ts
Can you use test naming convention? in this case .unit.test.ts? And, then add it to checkNamingScript?

2024-03-19 09:07 UTC, fabiorigam commented on apps/sdk-nextjs-integration/src/app/page.tsx
> +                        // eslint-disable-next-line @typescript-eslint/no-misused-promises
Yes, will fix it in the future

2024-03-19 09:22 UTC, rodolfopietro97 approved these changes

2024-03-19 10:07 UTC, merged