646 drop in replacement for etherjs toquantity method
vechain/vechain-sdk-js pull request #718
Opened 2024-03-15 20:20 UTC by lucanicoladebiasi

# Description

The code in `packages/core/src/utils/hex/Hex.ts` provides a drop-in replacement for the **ether.js Utilities** [toQuantity](https://docs.ethers.org/v6/api/utils/#toQuantity) function characterised to return an hexadecimal expression complying with the  [HexString](https://docs.ethers.org/v6/api/utils/#HexString) specifications:
- prefixed with `0x`,
- zero is represented as `0x0`,
- no `0` digit is in the expression if not meaningful.

# Fixes

In `packages/core/src/utils/hex/Hex.ts`

- `H0x.of` replaces `Hex.of0x` because previous function name made no sense, but open to better naming suggestion;
- `Quantity.of()` replaces **ether.js** `toQuantity()` in `math.ts` file, this is the goal of this ticket, see description above.
- Internal functions to convert specific TS types reworked for sake of efficiency, added specific methods for `Buffer` and `Uint8Array`.
- The **ether.js** library defines an `HexString` type as a pure alias of `string`: this is unfortunate because `HexString` should be a type having a `string` enforcing the regex pattern `/^0x[0-9A-Fa-f]*$/`. The rest of libraries using in the SDK are not aware of `HexString` semantics and they don't distinguish from `string` resulting in bugs. This ticket resolves the issue assuring strings are recognised as `HexString` when expressing a valid `0x` hexadecimal expression. The documentation explains how to force strings appearing as `HexString` to be considered an array of bytes when needed.

## Type of change

- [x] Enhancement: the `packages/core/src/utils/hex/Hex.ts` code provides a polymorphic pattern to render TS types into hexadecimal representations.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `yarn test:unit`
- [x] `yarn test:solo`

# Checklist:

- [x] My code follows the coding standards of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing integration tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-03-19 15:13 UTC, rodolfopietro97 requested changes
Hi @lucanicoladebiasi can you document Hex? In particular I don't understand what is 'H0x'.
You can add examples in docs.
More can you give back code coverage to 100%?
<img width="835" alt="image" src="https://github.com/vechain/vechain-sdk-js/assets/33911400/f8528a29-2700-4aac-a4a1-ca8d67bd1e85">

These branches are not covered (you need to call the functions with specify the parameter)

2024-03-19 16:53 UTC, lucanicoladebiasi commented on packages/core/src/utils/data/data.ts
> +    // toHexString,
Done.

2024-03-22 08:43 UTC, fabiorigam approved these changes

2024-03-22 08:58 UTC, rodolfopietro97 approved these changes

2024-03-22 08:58 UTC, merged