feat: hardhat custom ethers functionalities
vechain/vechain-sdk-js pull request #730
Opened 2024-03-20 10:20 UTC by rodolfopietro97

# Description

Implement missing hardhat ethers functionalities

2024-03-25 15:43 UTC, fabiorigam requested changes
Please increase coverage

2024-04-05 10:39 UTC, fabiorigam requested changes

2024-04-05 10:39 UTC, fabiorigam commented on apps/sdk-hardhat-integration/scripts/deploy.ts
> +    console.log('txResponse', JSON.stringify(txResponse));
DO we need all these console.log? Let's just keep one like "Contract x deployed to ..."

2024-04-05 10:39 UTC, fabiorigam commented on packages/ethers-adapter/README.md
> +
This is a copy and paste, please update the text

2024-04-05 10:39 UTC, fabiorigam commented on packages/ethers-adapter/package.json
> +  "description": "This module allows to create smart contracts and interact with them using the vechain SDK and Hardhat",
same here

2024-04-05 10:39 UTC, fabiorigam commented on packages/ethers-adapter/package.json
> +    "ethers",
update keywords

2024-04-05 10:39 UTC, fabiorigam commented on packages/ethers-adapter/src/adapters/contract-adapter.ts
> + */
missing @returns

2024-04-05 10:39 UTC, fabiorigam commented on packages/ethers-adapter/src/adapters/factory-adapter.ts
> + */
missing @returns

2024-04-05 10:39 UTC, fabiorigam commented on packages/ethers-adapter/src/adapters/helpers.ts
> + */
same

2024-04-05 14:16 UTC, Valazan commented on packages/ethers-adapter/README.md
> +
updated

2024-04-05 14:29 UTC, fabiorigam approved these changes

2024-04-05 14:29 UTC, merged