feat; add logging system for rpc proxy
vechain/vechain-sdk-js pull request #733
Opened 2024-03-20 11:07 UTC by rodolfopietro97

# Description

Add logging to RPC proxy in order to improve usability

2024-03-20 11:21 UTC, fabiorigam requested changes

2024-03-20 11:21 UTC, fabiorigam commented on packages/rpc-proxy/src/types.d.ts
> +     * Debug mode
We should add this debug property for logging inside the README.md and explain what it does. Personally, I would keep it as disabled by default, but anyway we need to explain this inside the README.md file as it's important.

2024-03-21 09:29 UTC, fabiorigam approved these changes

2024-03-22 08:58 UTC, rodolfopietro97 commented on packages/rpc-proxy/src/types.d.ts
> +     * Debug mode
https://github.com/vechain/vechain-sdk-js/pull/733/commits/99ecd04fd193641e5c7e8df4857711c07076e2b0

2024-03-22 09:56 UTC, merged