Signer Draft [WIP]
vechain/vechain-sdk-js pull request #758
Opened 2024-03-28 08:43 UTC by fabiorigam

Draft of Signer to collect feedback.

2024-03-28 09:09 UTC, darrenvechain commented
Looks good, 2 thoughts from my side.

1. First one is `TransactionSender` as its in the wallet package. I know I named that, but may make more sense to name it along the lines of a wallet, if its part of the wallet package.
2. The usage of the actual `TransactionSender`. I think the user will only have 1 signer in most cases. (Eg in the dapp kit, we will pass in 1 signer and manage the different wallets within that signer). Could we have an optional field in the thor client constructor to pass in the thor client? I guess to satsify this criteria:
- If the user passes the signer into the thor client, transactions and contracts should default to using the signer passed into thor client.
- If the user passes the signer into the thor client, and passes a signer into the individual transaction/contract, the signer passed into thor client get's overridden.
- If the user does NOT pass the signer into thor client, they must pass the signer into the individual methods/ modules?

Hopefully this makes sense. WDYT? I think it make thor client easier to use in most cases

Something along the lines of:

```typescript
//ThorClient

    private defaultTxSender?: TransactionSender
   
    constructor(
        readonly httpClient: HttpClient,
        txSender?: TransactionSender,
        options?: BlocksModuleOptions,
    ) {
        this.txSender = txSender
    }
    
// contracts
    public createContractFactory(
        abi: InterfaceAbi,
        bytecode: string,
        txHandler?: TransactionSender
    ): ContractFactory {
          
          let txSender: TransactionSender
          
          if (txHandler) {
                    txSender = txHandler
          } else {
                    txSender = this.defaultTxSender
          }

          if (!txSender) throw new Error("No transaction sender has been specified")


    }

2024-03-28 09:21 UTC, Valazan requested changes

2024-03-28 09:21 UTC, Valazan commented on packages/network/src/thor-client/contracts/contracts-module.ts
> +        console.log('clause', clause);
Remove console.log

2024-03-28 09:21 UTC, Valazan commented on packages/network/src/thor-client/contracts/contracts-module.ts
> +                return await this.thor.transactions.waitForTransaction(tx.id);
Simplify the statement with simply () => this.thor.transactions.waitForTransaction(tx.id)

2024-03-28 09:21 UTC, Valazan commented on packages/network/src/thor-client/contracts/model/contract-proxy.ts
> +                    throw new Error('Transaction sender is undefined.');
Throw custom errors according to our standard.

Like:

                if (contract.getCallerPrivateKey() === undefined) {
                    throw buildError(
                        'Contract.getTransactProxy',
                        ERROR_CODES.TRANSACTION.MISSING_PRIVATE_KEY,
                        'Caller private key is required to transact with the contract.',
                        { prop }
                    );
                }

2024-03-28 09:21 UTC, Valazan commented on packages/network/src/thor-client/contracts/model/contract.ts
> +        txSender?: TransactionSender,
This two method that have been removed are important, they let you change the signer when executing transactions, please redifine them

    /**
     * Sets the private key of the caller for signing transactions.
     * @param privateKey
     */
    public setCallerPrivateKey(privateKey: string): string {
        this.callerPrivateKey = privateKey;

        // initialize the proxy with the new private key
        this.transact = getTransactProxy(this);
        this.read = getReadProxy(this);
        return this.callerPrivateKey;
    }

    /**
     * Get the private key of the caller for signing transactions.
     * @returns The private key of the caller.
     */
    public getCallerPrivateKey(): string | undefined {
        return this.callerPrivateKey;
    }

2024-03-28 09:21 UTC, Valazan commented on packages/network/tests/thor-client/contracts/contract.erc20.solo.test.ts
> +        console.log(factory.getDeployTransaction());
remove console.log

2024-03-28 09:21 UTC, Valazan commented on packages/network/tests/thor-client/contracts/contract.solo.test.ts
> +    // test('Should filter the StateChanged event of the testing contract', async () => {
Remember to check why this is failing

2024-03-28 13:11 UTC, darrenvechain commented on packages/network/src/thor-client/contracts/model/contract.ts
> +        txSender?: TransactionSender,
@Valazan it may be better have `contract.attach(signer)` that will return a new contract instance

2024-04-02 05:34 UTC, rodolfopietro97 requested changes

2024-04-02 05:34 UTC, rodolfopietro97 commented on docs/contracts-erc20.md
> +const pksigner = new PrivateKeySigner(
chore: Can you use better names? e.g. privateKeySigner?

2024-04-02 05:34 UTC, rodolfopietro97 commented on docs/examples/contracts/contract-create-ERC20-token.ts
> +const pksigner = new PrivateKeySigner(
chore: Can you use better names? e.g. privateKeySigner?

2024-04-02 05:34 UTC, rodolfopietro97 commented on docs/examples/contracts/contract-deposit.ts
> +const pksigner = new PrivateKeySigner(
chore: Can you use better names? e.g. privateKeySigner?

2024-04-02 05:34 UTC, rodolfopietro97 commented on docs/examples/contracts/contract-transfer-ERC20-token.ts
> +const pksigner = new PrivateKeySigner(
chore: Can you use better names? e.g. privateKeySigner?

2024-04-02 05:34 UTC, rodolfopietro97 commented on packages/wallet/src/signers/types.d.ts
> +interface Signer {
Some doubts on signer interface.
Aim of signer is to offer the standard structure of ethers.js. 
Basically a signer is an abstraction of an account, able to sign and send transaction.
Currently we used wallet class to do that.
Aim of signer class is to have same constructs of ethers.
So:
* Can you implement in this interface ethers.js signer?
* Can you add delegation methods? e.g. sendWithDelegator, ...?
* More signer has some other methods

2024-04-03 07:47 UTC, fabiorigam commented
Worked on Signer on another branch

2024-04-03 07:47 UTC, closed without merging