feat: implement simple signer
vechain/vechain-sdk-js pull request #787
Opened 2024-04-09 13:37 UTC by rodolfopietro97

# Description

Implement signer

# Checklist:

- [ ] Abstract signer
- [ ] Test signer
- [ ] Simple implementation of abstract signer
- [ ] Proper ethers.TransactionResponse implementation (understand if do it in this task or not)
- [ ] Document difference between Signer, Provider and Wallet in order to have a clear and simple user experience

2024-04-15 13:40 UTC, fabiorigam requested changes

2024-04-15 13:40 UTC, fabiorigam commented on .changeset/funny-masks-cheat.md
>  "@vechain/sdk-logging": patch
Can you explain why you removed these lines?

2024-04-15 13:40 UTC, fabiorigam commented on .github/workflows/publish-sdk.yml
> -              run: |
Same here

2024-04-16 09:39 UTC, lucanicoladebiasi approved these changes

2024-04-16 11:10 UTC, rodolfopietro97 commented on .changeset/funny-masks-cheat.md
>  "@vechain/sdk-logging": patch
Because these package will be removed. So no need to publish them

2024-04-16 11:10 UTC, rodolfopietro97 commented on .github/workflows/publish-sdk.yml
> -              run: |
Because these package will be removed. So no need to publish them

2024-04-16 12:17 UTC, fabiorigam reviewed
Please make sure that removed packages do not appear anymore on README.md files, diagrams an so on...

2024-04-16 13:33 UTC, fabiorigam approved these changes

2024-04-16 13:35 UTC, merged