refactor: 666 pure and secure units.ts
vechain/vechain-sdk-js pull request #874
Opened 2024-05-15 17:41 UTC by lucanicoladebiasi

# Description

The code at `packages/core/src/utils/units` delivers a drop-in replacement for the `ethers` lib functions parsing and formatting *wei* units.

The code promotes the use of MIT licensed [bignumber.js](https://mikemcl.github.io/bignumber.js/) library to provide fixed precision math to deal with monetary amounts.

The test code at `packages/core/tests/utils/units/units.unit.test.ts` splits test loops in independent tests easy the tests of fixed precision math and librieries.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `yarn test:solo`
- [x] `yarn test:unit`

**Test Configuration**:
* Node.js Version: 1.22.22
* Yarn Version: v21.6.2

# Checklist:

- [x] My code follows the coding standards of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing integration tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-05-16 08:05 UTC, rodolfopietro97 requested changes

2024-05-16 08:05 UTC, rodolfopietro97 commented on packages/core/tests/utils/units/units.unit.test.ts
> +        test('invalid - not a number - decimal', () => {
@lucanicoladebiasi Can I suggest to make fixture files and iterate over them? Basically to repeat less code and to add easily test cases

2024-05-16 08:59 UTC, lucanicoladebiasi commented on packages/core/tests/utils/units/units.unit.test.ts
> +        test('invalid - not a number - decimal', () => {
I'm keen to don't accept the suggestion. It seems the code introduce redundancy, but in the reality having a single test per expectations made my work much easier to assess which of the math libraries (big, bignumber, decimal) worked correctly reverse engineering the weird internal FixedPrecision class of `ethers`.
The jest framework with its capability to nest `describe` and `test` methods offers the same iterability of of the a collection of test cases as fixture but with the convenience to pick which case to test, experimenting precisely what I want to test. At the contrary to modify the code executing a loop of test cases was annoying and forced conversions of data type to fit in the collection of the fixture made me to easy to forget some case to test.

2024-05-16 09:48 UTC, lucanicoladebiasi commented on packages/core/tests/utils/units/units.unit.test.ts
> +        test('invalid - not a number - decimal', () => {
Pair programmed with @rodolfopietro97 to fix` assert` with bigint and `toThrowError` behaviour, we appreciated the possibility to pinpoint tests hence in this case we agreed to keep the tests as here proposed for this case.

2024-05-17 09:00 UTC, rodolfopietro97 approved these changes

2024-05-20 17:51 UTC, merged