943 certificate sign/verify eip55 thor-devkit compatibility
vechain/vechain-sdk-js pull request #985
Opened 2024-06-13 18:06 UTC by lucanicoladebiasi

# Description

The code at `packages/core/src/certificate/certificate.ts` introduces
* the `sign` method to encapsulate the logic encoding a `Certificate` instance to its byte array representation;
* the `verify` method is compatible with the certificates built by with **thor-devkit** if the the certificate doesn't include text occurring in https://en.wikipedia.org/wiki/Unicode_equivalence ambiguities.

The tests at `packages/core/tests/certificate/certificate.unit.test.ts`
* include challenges certificates involving Unicode ambiguities;
* include tests to assure **thor-devkit** compatibility, those must be uncommented because the dependency from **thor-devkit** introduce an resolved lint rule not allowing the import of the `bignumber.js` library.

NOTE: The `sign` method is introduced to avoid ambiguities in the transformation of a certificate from object to its byte representation through JSON and UTF8 encoding and decoding. If no UTF normalisation is enforced, 'high' Unicode planes (ideograms, emoticons) are not consistently represented with the same bytes because the normalisation is demanded to the runtime. 

## Fixes # 943

* `sign` enforces UTF8 Normalization Form Canonical Composition to compute the signature.
* `verify` is insensitive about the signer address case (but the equivalent **thor-devkit** code is not).
* `sign` and `verify` functions ignores additional properties introduced if the certificate instance extends the `Certificate` interface: the signature is computed only on the basis of the properties defined in the `Certificate` interface.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `yarn test:solo`

**Test Configuration**:
* Node.js Version: v20.24.0
* Yarn Version: 1.22.22

# Checklist:

- [x] My code follows the coding standards of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing integration tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-06-14 07:22 UTC, rodolfopietro97 requested changes

2024-06-14 07:22 UTC, rodolfopietro97 commented on packages/core/tests/certificate/certificate.unit.test.ts
> +        // NOTE: UNCOMMENT BELOW TO TEST THOR-DEVKIT COMPATIBILITY.
Hey @lucanicoladebiasi why take these test commented?

2024-06-14 08:44 UTC, claytonneal commented on packages/core/tests/certificate/certificate.unit.test.ts
> +// NOTE: UNCOMMENT BELOW TO TEST THOR-DEVKIT COMPATIBILITY.
can we have this test there by default?

2024-06-14 08:45 UTC, claytonneal commented on packages/core/tests/certificate/certificate.unit.test.ts
> +        //         )
can this be uncommented?

2024-06-14 11:45 UTC, lucanicoladebiasi commented on packages/core/tests/certificate/certificate.unit.test.ts
> +        // NOTE: UNCOMMENT BELOW TO TEST THOR-DEVKIT COMPATIBILITY.
Becuase if I introduce the dependency from `thor-devkit`  yarn lint "goes Texas" or 'go nuts" that is the expressions used in North Europe to mean the Italian "da di matto", and I hadn't find a solution yet. This is the reason the PR is in draft, I do need the support of you and our colleagues to understand why `thor-devkit` interfers with `bignumber.js`.

2024-06-14 11:46 UTC, lucanicoladebiasi commented on packages/core/tests/certificate/certificate.unit.test.ts
> +// NOTE: UNCOMMENT BELOW TO TEST THOR-DEVKIT COMPATIBILITY.
Yes, I want it, but as I wrote in the PR descriptions, I can't solve a clash of dependencies with `thor-devkit` and I need your experience to help.

2024-06-14 11:48 UTC, lucanicoladebiasi commented on packages/core/tests/certificate/certificate.unit.test.ts
> +        //         )
I wish the same, but I need your help to control a dependency clash because `thor-devkit`, I spent 2 days to find a solution and I decided to push a PR in draft because unable to solve the problem alone.

2024-06-14 18:15 UTC, lucanicoladebiasi commented on packages/core/tests/certificate/certificate.unit.test.ts
> +        // NOTE: UNCOMMENT BELOW TO TEST THOR-DEVKIT COMPATIBILITY.
Agreed to keep **thor-devkit** tests commented until the problem introduced because its **thor-devkit** dependencies are solved.

2024-06-14 18:17 UTC, lucanicoladebiasi commented on packages/core/tests/certificate/certificate.unit.test.ts
> +// NOTE: UNCOMMENT BELOW TO TEST THOR-DEVKIT COMPATIBILITY.
@rodolfopietro97 and I reviewed the problems introuced by **thor-devkit** dependencies and we agreed to postpone the solution opening a dedicated ticket to release this code the sooner.

2024-06-14 18:18 UTC, lucanicoladebiasi commented on packages/core/tests/certificate/certificate.unit.test.ts
> +        //         )
See the comment above. We must change **lint** configuration to blend **thor0devkit** dependencies in the test code.

2024-06-14 18:22 UTC, lucanicoladebiasi commented
Accurate revision with @rodolfopietro97 shows the introduction of **thor-devkit** dependency in test code messes **lint** behaviour. Lint configuration must be changed, a specific ticket will be assigned for the task. Rodolfo and I decided to proceed to promote this PR to review to include the fixes.

2024-06-17 09:16 UTC, rodolfopietro97 approved these changes

2024-06-17 09:18 UTC, merged